<?php
/**
 * Implements hook_form_alter().
 */
 function mymodule_form_alter(&$form,\Drupal\Core\Form\FormStateInterface $form_state, $form_id){
     //dpm("hello");
      if($form_id == 'comment_comment_form'){
          $form['actions']['submit']['#value'] = t('Comment');
      }
 }

 function mymodule_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'mymodule/mymodule_lib';
}
